class Values {

static const  List<String> platforms = [

    "ALL",
  "OTHER",
    "VN",
    "CAPCUT",
    "AFTER EFFECTS",
    "PREMIERE PRO",
    "LIGHTROOM",
    "PHOTOSHOP",
    "ILLUSTRATOR",
    "INDESIGN",
    "ADOBE XD",
    "FINAL CUT PRO",
    "DAVINCI RESOLVE",
    "FILMORA",
    "KINE MASTER",
    "IMOVIE"
  ];

static const List<String> fileCategories = [
  "other",
  "overlay",
  "lr preset",
  "template",
  "preset",
  "psd",
  "image",
  "video",
  "mp3",
  "wav",
  "sfx",
  "fonts",
  "svg",
  "png",
  "jpeg",
  "gif",
  "motion graphics",
  "3d model",
  "lut",
  "transition pack",
  "brush pack",
  "icons",
  "texture",
  "pattern",
  "mockup",
  "animated template",
  "plugins",
  "scripts",
  "audio pack",
  "background music",
  "cinematic sound effects",
  "color grading presets",
  "intro template",
  "outro template",
  "lower third",
  "titles pack",
  "splash screen",
  "stock footage",
  "green screen effects",
  "call to action buttons",
  "ui/ux kits",
  "web elements",
  "infographics",
  "vector pack",
  "3d text effects",
  "stickers pack",
  "emojis pack",
  "social media template",
  "thumbnail template",
  "mobile app ui design",
  "after effects preset",
  "premiere pro preset",
  "lightroom profile",
  "photoshop actions",
  "illustrator brushes",
  "gaming assets",
  "game account",
  "nft",
  "crypto assets",
  "metaverse items",
  "ai-generated art",
  "vr/ar assets",
  "e-book",
  "pdf template",
  "resume template",
  "presentation template",
  "business card template",
  "logo template",
  "website template",
  "notion template",
  "canva template",
  "motion presets",
  "text animation pack",
  "cartoon effects",
  "handwritten fonts",
  "calligraphy fonts",
  "digital paintings",
  "character illustrations",
  "pixel art",
  "isometric illustrations",
  "animated stickers",
  "emoji animations",
  "game sprites",
  "soundtracks",
  "custom sound effects",
  "twitch overlays",
  "streaming assets",
  "video editing project files",
  "social media highlight covers",
  "powerpoint template",
  "google slides template"
];

}

class UserDefaults {
  // Default fields for a new user document
  static Map<String, dynamic> get defaultFields => {
    'assetsFREE': [], // Default empty list
    'assetsPURCHASED': [], // Default empty list
    'products': [], // Default empty list (can be added in the future)
  };
}