// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4esg31eZOh2j0bvQhQkaFr-CL2HRw-tw',
    appId: '1:920543984860:web:e4758ad77a3e75777a0819',
    messagingSenderId: '920543984860',
    projectId: 'asset-56406',
    authDomain: 'asset-56406.firebaseapp.com',
    storageBucket: 'asset-56406.firebasestorage.app',
    measurementId: 'G-MDD020WKJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpEaMm9I_cZCQj_aFVfkaYwBo2tOAPc08',
    appId: '1:920543984860:android:6938e58d072861617a0819',
    messagingSenderId: '920543984860',
    projectId: 'asset-56406',
    storageBucket: 'asset-56406.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4jkVwi3zWpl8wwVKX4CYAuAVPgW-3NHc',
    appId: '1:920543984860:ios:f3618eada2e078f87a0819',
    messagingSenderId: '920543984860',
    projectId: 'asset-56406',
    storageBucket: 'asset-56406.firebasestorage.app',
    iosBundleId: 'com.cactus.asset.asset',
  );
}
