import 'package:asset/Models/asset_model/asset_model.dart';

AssetModel freeDummyAsset = AssetModel(
  author: "Creativeaaaaaaaa",
  link: "https://example.com/reel",
  fileExtension: ".mp4",
  downloadLink: "https://www.dropbox.com/scl/fi/7le3tbjtlxvt5586vhzp0/asset-moodyglow.zip?rlkey=c3yw1nkr6f15dz71qzma0qmwe&st=asll080j&dl=1",
  name: "Sunset Over the Mountainsddddddddddddddddd",
  platform: "Pexelaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaas",
  size: 4532.7, // Size in MB
  price: 0.0, // Free asset
  status: "FREE",
  fileCategory: "video",
  hidden: false, // Replace with actual logo URL
);

AssetModel paidDummyAsset2 = AssetModel(
  author: "Creative cloud",
  link: "https://example.com/reel",
  fileExtension: ".mp4",
  downloadLink: "https://www.dropbox.com/scl/fi/7le3tbjtlxvt5586vhzp0/asset-moodyglow.zip?rlkey=c3yw1nkr6f15dz71qzma0qmwe&st=asll080j&dl=1",
  name: "Sunset Over ",
  platform: "Pexels",
  size: 435.7, // Size in MB
  price: 0.0, // Free asset
  status: "PAID",
  fileCategory: "video",
  hidden: false, // Replace with actual logo URL
);



List<AssetModel> dummyAssets = [
  AssetModel(
    author: "Creative Author 1",
    link: "https://example.com/reel1",
    fileExtension: ".mp4",
    downloadLink: "https://www.dropbox.com/scl/fi/7le3tbjtlxvt5586vhzp0/asset-moodyglow.zip?rlkey=c3yw1nkr6f15dz71qzma0qmwe&st=asll080j&dl=1",
    name: "Asset 1",
    platform: "Pexels",
    size: 50.0,
    price: 0.0,
    status: "FREE",
    fileCategory: "video",
    hidden: false,
  ),
  AssetModel(
    author: "Creative Author 2",
    link: "https://example.com/reel2",
    fileExtension: ".mp4",
    downloadLink: "https://www.dropbox.com/scl/fi/7le3tbjtlxvt5586vhzp0/asset-moodyglow.zip?rlkey=c3yw1nkr6f15dz71qzma0qmwe&st=asll080j&dl=1",
    name: "Asset 2",
    platform: "Pexels",
    size: 75.0,
    price: 0.0,
    status: "FREE",
    fileCategory: "video",
    hidden: false,
  ),
  AssetModel(
    author: "Creative Author 3",
    link: "https://example.com/reel3",
    fileExtension: ".mp4",
    downloadLink: "https://www.dropbox.com/scl/fi/7le3tbjtlxvt5586vhzp0/asset-moodyglow.zip?rlkey=c3yw1nkr6f15dz71qzma0qmwe&st=asll080j&dl=1",
    name: "Asset 3",
    platform: "Pexels",
    size: 100.0,
    price: 0.0,
    status: "FREE",
    fileCategory: "video",
    hidden: false,
  ),
  AssetModel(
    author: "Creative Author 4",
    link: "https://example.com/reel4",
    fileExtension: ".mp4",
    downloadLink: "https://www.dropbox.com/scl/fi/7le3tbjtlxvt5586vhzp0/asset-moodyglow.zip?rlkey=c3yw1nkr6f15dz71qzma0qmwe&st=asll080j&dl=1",
    name: "Asset 4",
    platform: "Pexels",
    size: 125.0,
    price: 0.0,
    status: "FREE",
    fileCategory: "video",
    hidden: false,
  ),
  AssetModel(
    author: "Creative Author 5",
    link: "https://example.com/reel5",
    fileExtension: ".mp4",
    downloadLink: "https://www.dropbox.com/scl/fi/7le3tbjtlxvt5586vhzp0/asset-moodyglow.zip?rlkey=c3yw1nkr6f15dz71qzma0qmwe&st=asll080j&dl=1",
    name: "Asset 5",
    platform: "Pexels",
    size: 150.0,
    price: 0.0,
    status: "FREE",
    fileCategory: "video",
    hidden: false,
  ),
  // More free assets
  AssetModel(
    author: "Creative Author 6",
    link: "https://example.com/reel6",
    fileExtension: ".mp4",
    downloadLink: "https://www.dropbox.com/scl/fi/7le3tbjtlxvt5586vhzp0/asset-moodyglow.zip?rlkey=c3yw1nkr6f15dz71qzma0qmwe&st=asll080j&dl=1",
    name: "Asset 6",
    platform: "Pexels",
    size: 175.0,
    price: 0.0,
    status: "FREE",
    fileCategory: "video",
    hidden: false,
  ),
  AssetModel(
    author: "Creative Author 7",
    link: "https://example.com/reel7",
    fileExtension: ".mp4",
    downloadLink: "https://www.dropbox.com/scl/fi/7le3tbjtlxvt5586vhzp0/asset-moodyglow.zip?rlkey=c3yw1nkr6f15dz71qzma0qmwe&st=asll080j&dl=1",
    name: "Asset 7",
    platform: "Pexels",
    size: 200.0,
    price: 0.0,
    status: "FREE",
    fileCategory: "video",
    hidden: false,
  ),
  // 3 more free assets...

  // Paid Assets
  AssetModel(
    author: "Creative Author 11",
    link: "https://example.com/reel11",
    fileExtension: ".mp4",
    downloadLink: "https://www.dropbox.com/scl/fi/7le3tbjtlxvt5586vhzp0/asset-moodyglow.zip?rlkey=c3yw1nkr6f15dz71qzma0qmwe&st=asll080j&dl=1",
    name: "Asset 11",
    platform: "Pexels",
    size: 300.0,
    price: 10.0,
    status: "PAID",
    fileCategory: "video",
    hidden: false,
  ),
  AssetModel(
    author: "Creative Author 12",
    link: "https://example.com/reel12",
    fileExtension: ".mp4",
    downloadLink: "https://www.dropbox.com/scl/fi/7le3tbjtlxvt5586vhzp0/asset-moodyglow.zip?rlkey=c3yw1nkr6f15dz71qzma0qmwe&st=asll080j&dl=1",
    name: "Asset 12",
    platform: "Pexels",
    size: 350.0,
    price: 15.0,
    status: "PAID",
    fileCategory: "video",
    hidden: false,
  ),
  AssetModel(
    author: "Creative Author 13",
    link: "https://example.com/reel13",
    fileExtension: ".mp4",
    downloadLink: "https://www.dropbox.com/scl/fi/7le3tbjtlxvt5586vhzp0/asset-moodyglow.zip?rlkey=c3yw1nkr6f15dz71qzma0qmwe&st=asll080j&dl=1",
    name: "Asset 13",
    platform: "Pexels",
    size: 400.0,
    price: 20.0,
    status: "PAID",
    fileCategory: "video",
    hidden: false,
  ),
  AssetModel(
    author: "Creative Author 14",
    link: "https://example.com/reel14",
    fileExtension: ".mp4",
    downloadLink: "https://www.dropbox.com/scl/fi/7le3tbjtlxvt5586vhzp0/asset-moodyglow.zip?rlkey=c3yw1nkr6f15dz71qzma0qmwe&st=asll080j&dl=1",
    name: "Asset 14",
    platform: "Pexels",
    size: 450.0,
    price: 25.0,
    status: "PAID",
    fileCategory: "video",
    hidden: false,
  ),
  // 6 more paid assets...
];
